### PR TITLE
Increment prevTime before calling rAF callback

### LINKED ISSUE #10: mockRaf.now() fails to increase before callback is called
```js
var createMockRaf = require('mock-raf');
var mockRaf = createMockRaf();
let frameTime = mockRaf.now();
mockRaf.raf(function frameLoop() {
  const lastFrameTime = frameTime;
  frameTime = mockRaf.now();
  console.assert(frameTime > lastFrameTime); // this fails, but shouldn't
});
mockRaf.step();
```

### PR DESCRIPTION
**Pull request by jcready**
Fixes #10

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -33,13 +33,13 @@ module.exports = function () {
     for (var i = 0; i < options.count; i++) {
       oldAllCallbacks = allCallbacks;
       allCallbacks = {};
+      
+      prevTime += options.time;
 
       Object.keys(oldAllCallbacks).forEach(function (id) {
         var callback = oldAllCallbacks[id];
         callback(prevTime + options.time);
```
Comment (alexlande) [inline index.js]: This should just be `callback(prevTime)` with this change, right?

**Comment by alexlande** [comment]
Thanks for the patch, this is great 👍

**Comment by alexlande** [comment]
Published as v1.0.1
